# Generated by Django 4.2.16 on 2024-11-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbstractObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observatory", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="CelestialTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("coordinates", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ExoplanetObservation",
            fields=[
                (
                    "abstractobservation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="observations.abstractobservation",
                    ),
                ),
                ("filter_set", models.CharField(max_length=100)),
            ],
            bases=("observations.abstractobservation",),
        ),
        migrations.AddField(
            model_name="abstractobservation",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="observations.celestialtarget",
            ),
        ),
    ]
