services:
  db:
    image: postgres
    volumes:
      - ${DB_VOLUME:-db-data}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  web:
    build: .
    command: >
      sh -c "./scripts/wait-for-it.sh db:5432 -t 120 -- python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./scripts/wait-for-it.sh:/scripts/wait-for-it.sh
    ports:
      - "${WEB_PORT}:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  nextcloud:
    image: nextcloud
    profiles:
      - test
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: admin
    ports:
      - "${NEXTCLOUD_PORT}:80"

volumes:
  db-data: { }
