# Generated by Django 5.1.3 on 2025-01-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invitationtoken",
            options={},
        ),
        migrations.AlterModelOptions(
            name="observatoryuser",
            options={
                "permissions": [
                    ("can_generate_invitation", "Can generate invitation links"),
                    ("can_invite_admins", "Can invite new admin users"),
                    ("can_invite_group_leaders", "Can invite new group leaders"),
                    ("can_create_expert_observation", "Can create expert observation"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="invitationtoken",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("group_leader", "Gruppenleiter")],
                max_length=100,
                null=True,
            ),
        ),
    ]
