# Generated by Django 5.1.3 on 2025-01-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_invitationtoken_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationtoken",
            name="expert",
            field=models.BooleanField(default=False),
        ),
    ]
