# Generated by Django 5.1.5 on 2025-02-02 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_observatoryuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observatoryuser",
            options={
                "permissions": [
                    ("can_generate_invitation", "Can generate invitation links"),
                    ("can_invite_admins", "Can invite new admin users"),
                    ("can_invite_operators", "Can invite new operators"),
                    ("can_create_expert_observation", "Can create expert observation"),
                    ("can_see_all_observations", "Can see all observations"),
                    ("can_edit_all_observations", "Can edit all observations"),
                    ("can_delete_all_observations", "Can delete all observations"),
                ]
            },
        ),
    ]
