# Generated by Django 5.1.3 on 2025-01-22 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_invitationtoken_expert"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observatoryuser",
            options={
                "permissions": [
                    ("can_generate_invitation", "Can generate invitation links"),
                    ("can_invite_admins", "Can invite new admin users"),
                    ("can_invite_group_leaders", "Can invite new group leaders"),
                    ("can_create_expert_observation", "Can create expert observation"),
                    ("can_see_all_observations", "Can see all observations"),
                ]
            },
        ),
    ]
