# Generated by Django 5.1.3 on 2025-01-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_observatoryuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="observatoryuser",
            name="deletion_pending",
            field=models.BooleanField(default=False),
        ),
    ]
