# Generated by Django 5.1.3 on 2025-01-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_observatoryuser_deletion_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationtoken",
            name="username",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
