# Generated by Django 5.1.3 on 2025-02-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_observatoryuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observatoryuser",
            name="username",
            field=models.CharField(max_length=150),
        ),
    ]
