# Generated by Django 5.1.3 on 2025-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_invitationtoken_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitationtoken",
            name="link",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
