# Generated by Django 5.1.3 on 2025-01-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitationtoken",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("group_leader", "group_leader")],
                max_length=100,
                null=True,
            ),
        ),
    ]
