# Generated by Django 5.1.3 on 2024-11-17 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_type",
                    models.CharField(
                        choices=[
                            ("Imaging", "Imaging"),
                            ("Exoplanet", "Exoplanet"),
                            ("Variable", "Variable"),
                            ("Monitoring", "Monitoring"),
                            ("Expert", "Expert"),
                        ],
                        db_column="type",
                    ),
                ),
                ("project_status", models.CharField(max_length=50)),
                ("priority", models.IntegerField()),
                ("exposure_time", models.DecimalField(decimal_places=2, max_digits=10)),
                ("filter_set", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CelestialTarget",
            fields=[
                (
                    "catalog_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("ra", models.CharField(max_length=25)),
                ("dec", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Observatory",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("horizonOffset", models.DecimalField(decimal_places=2, max_digits=5)),
                ("min_stars", models.IntegerField()),
                ("max_HFR", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "max_guide_error",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("filter_Set", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ExoplanetObservation",
            fields=[
                (
                    "abstractobservation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="observation_data.abstractobservation",
                    ),
                ),
                ("start_observation", models.DateTimeField()),
                ("end_observation", models.DateTimeField()),
            ],
            bases=("observation_data.abstractobservation",),
        ),
        migrations.CreateModel(
            name="ExpertObservation",
            fields=[
                (
                    "abstractobservation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="observation_data.abstractobservation",
                    ),
                ),
                ("frames_per_filter", models.IntegerField()),
                ("dither_every", models.DecimalField(decimal_places=2, max_digits=5)),
                ("binning", models.CharField(max_length=50)),
                ("subframe", models.CharField(max_length=50)),
                ("gain", models.IntegerField()),
                ("offset", models.IntegerField()),
                ("start_observation", models.DateTimeField()),
                ("end_observation", models.DateTimeField()),
                ("start_scheduling", models.DateTimeField()),
                ("end_scheduling", models.DateTimeField()),
                ("cadence", models.DurationField()),
                (
                    "moon_separation_angle",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("moon_separation_width", models.IntegerField()),
                (
                    "minimum_altitude",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            bases=("observation_data.abstractobservation",),
        ),
        migrations.CreateModel(
            name="ImagingObservation",
            fields=[
                (
                    "abstractobservation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="observation_data.abstractobservation",
                    ),
                ),
                ("frames_per_filter", models.IntegerField()),
            ],
            bases=("observation_data.abstractobservation",),
        ),
        migrations.CreateModel(
            name="MonitoringObservation",
            fields=[
                (
                    "abstractobservation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="observation_data.abstractobservation",
                    ),
                ),
                ("frames_per_filter", models.IntegerField()),
                ("start_scheduling", models.DateTimeField()),
                ("end_scheduling", models.DateTimeField()),
                ("cadence", models.DurationField()),
            ],
            bases=("observation_data.abstractobservation",),
        ),
        migrations.CreateModel(
            name="VariableObservation",
            fields=[
                (
                    "abstractobservation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="observation_data.abstractobservation",
                    ),
                ),
                (
                    "minimum_altitude",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
            bases=("observation_data.abstractobservation",),
        ),
        migrations.AddField(
            model_name="abstractobservation",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observation_data.celestialtarget",
            ),
        ),
        migrations.AddField(
            model_name="abstractobservation",
            name="observatory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observation_data.observatory",
            ),
        ),
    ]
