# Generated by Django 5.1.3 on 2024-11-17 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observatory",
            old_name="filter_Set",
            new_name="filter_set",
        ),
    ]
