# Generated by Django 5.1.3 on 2024-11-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abstractobservation",
            name="observatory",
            field=models.ForeignKey(
                db_column="observatory",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="observation_data.observatory",
            ),
        ),
    ]
