# Generated by Django 5.1.3 on 2024-11-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertobservation",
            name="required_amount",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="imagingobservation",
            name="required_amount",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoringobservation",
            name="required_amount",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variableobservation",
            name="required_amount",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
