# Generated by Django 5.1.3 on 2025-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertobservation",
            name="subframe",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
