# Generated by Django 5.1.4 on 2024-12-13 11:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expertobservation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="monitoringobservation",
            options={},
        ),
    ]
