# Generated by Django 5.1.3 on 2024-11-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abstractobservation",
            name="filter_set",
        ),
        migrations.AddField(
            model_name="abstractobservation",
            name="filter_set",
            field=models.ManyToManyField(
                related_name="observations", to="observation_data.filter"
            ),
        ),
    ]
