# Generated by Django 5.1.3 on 2024-11-18 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0002_abstractobservation_progress_completion_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="abstractobservation",
            old_name="progress_completion",
            new_name="project_completion",
        ),
    ]
