# Generated by Django 5.1.3 on 2024-12-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0002_alter_expertobservation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertobservation",
            name="next_upload",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monitoringobservation",
            name="next_upload",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
