# Generated by Django 5.1.3 on 2025-01-15 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0003_expertobservation_next_upload_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variableobservation",
            old_name="required_amount",
            new_name="frames_per_filter",
        ),
        migrations.RemoveField(
            model_name="expertobservation",
            name="required_amount",
        ),
        migrations.RemoveField(
            model_name="imagingobservation",
            name="required_amount",
        ),
        migrations.RemoveField(
            model_name="monitoringobservation",
            name="required_amount",
        ),
    ]
