# Generated by Django 5.1.3 on 2024-11-18 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "observation_data",
            "0003_rename_progress_completion_abstractobservation_project_completion",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="abstractobservation",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 18, 17, 40, 56, 713401)
            ),
            preserve_default=False,
        ),
    ]
