# Generated by Django 5.1.5 on 2025-02-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0004_rename_subframe_exposuresettings_subframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exposuresettings",
            name="subframe",
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
