# Generated by Django 5.1.3 on 2024-12-03 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0004_alter_abstractobservation_options_and_more"),
        ("observation_data", "0004_alter_exposuresettings_subframe"),
    ]

    operations = []
