# Generated by Django 5.1.3 on 2024-11-21 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0004_abstractobservation_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExposureSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gain", models.IntegerField()),
                ("offset", models.IntegerField()),
                ("binning", models.IntegerField()),
                ("subFrame", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Filter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("L", "Luminance"),
                            ("R", "Red"),
                            ("G", "Green"),
                            ("B", "Blue"),
                            ("H", "Hydrogen"),
                            ("O", "Oxygen"),
                            ("S", "Sulfur"),
                            ("SR", "Sr"),
                            ("SG", "Sg"),
                            ("SI", "Si"),
                        ],
                        db_column="type",
                        max_length=2,
                    ),
                ),
                (
                    "moon_separation_angle",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("moon_separation_width", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="expertobservation",
            name="subframe",
        ),
        migrations.AlterField(
            model_name="celestialtarget",
            name="catalog_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name="observatory",
            name="filter_set",
        ),
        migrations.CreateModel(
            name="ObservatoryExposureSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation_type",
                    models.CharField(
                        choices=[
                            ("Imaging", "Imaging"),
                            ("Exoplanet", "Exoplanet"),
                            ("Variable", "Variable"),
                            ("Monitoring", "Monitoring"),
                            ("Expert", "Expert"),
                        ],
                        db_column="type",
                    ),
                ),
                (
                    "exposure_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="observation_data.exposuresettings",
                    ),
                ),
                (
                    "observatory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="observation_data.observatory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="observatory",
            name="exposure_settings",
            field=models.ManyToManyField(
                related_name="observatories",
                through="observation_data.ObservatoryExposureSettings",
                to="observation_data.exposuresettings",
            ),
        ),
        migrations.AddField(
            model_name="observatory",
            name="filter_set",
            field=models.ManyToManyField(
                related_name="observatories", to="observation_data.filter"
            ),
        ),
    ]
