# Generated by Django 5.1.3 on 2025-02-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0005_alter_exposuresettings_subframe"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringobservation",
            name="minimum_altitude",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
