# Generated by Django 5.1.3 on 2024-11-21 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0005_exposuresettings_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observatoryexposuresettings",
            name="exposure_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="observation_data.exposuresettings",
            ),
        ),
        migrations.AlterField(
            model_name="observatoryexposuresettings",
            name="observatory",
            field=models.ForeignKey(
                db_column="observatory",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="observation_data.observatory",
            ),
        ),
    ]
