# Generated by Django 5.1.3 on 2024-12-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "observation_data",
            "0005_alter_abstractobservation_observation_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="celestialtarget",
            name="catalog_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="filter",
            name="filter_type",
            field=models.CharField(
                choices=[
                    ("L", "Luminance"),
                    ("R", "Red"),
                    ("G", "Green"),
                    ("B", "Blue"),
                    ("H", "Hydrogen"),
                    ("O", "Oxygen"),
                    ("S", "Sulfur"),
                    ("SR", "Sloan R"),
                    ("SG", "Sloan G"),
                    ("SI", "Sloan I"),
                ],
                db_column="type",
                max_length=2,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
