# Generated by Django 5.1.3 on 2025-02-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0005_alter_exposuresettings_subframe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="filter_type",
            field=models.CharField(
                db_column="type", max_length=2, primary_key=True, serialize=False
            ),
        ),
    ]
