# Generated by Django 5.1.3 on 2024-12-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "observation_data",
            "0006_celestialtarget_catalog_id_alter_filter_filter_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertobservation",
            name="binning",
            field=models.IntegerField(),
        ),
    ]
