# Generated by Django 5.1.3 on 2024-12-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0007_alter_expertobservation_binning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expertobservation",
            name="dither_every",
            field=models.IntegerField(),
        ),
    ]
