# Generated by Django 5.1.3 on 2025-02-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0007_monitoringobservation_minimum_altitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filter",
            name="filter_type",
            field=models.CharField(
                db_column="type", max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
