# Generated by Django 5.1.4 on 2024-12-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation_data', '0009_merge_20241213_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertobservation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='monitoringobservation',
            options={},
        ),
    ]
