# Generated by Django 5.1.3 on 2025-04-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("observation_data", "0012_expertobservation_batch_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abstractobservation",
            name="project_status",
            field=models.CharField(
                choices=[
                    ("Pending Upload", "Pending"),
                    ("Uploaded", "Uploaded"),
                    ("Error", "Error"),
                    ("Completed", "Completed"),
                    ("Pending Deletion", "Pending Deletion"),
                    ("Pending Completion", "Pending Completion"),
                    ("Failed", "Failed"),
                    ("Paused", "Paused"),
                ]
            ),
        ),
    ]
