name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
env:
  POSTGRES_DB: TURMFrontend
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
  ADMIN_EMAIL: admin@gmail.com
  ADMIN_PASSWORD: admin
jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: TURMFrontend
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      - name: Check python code formatting
        run: ruff format --check
      - name: Check for python lints
        run: ruff check --output-format=github .
      - name: Check Django template formatting
        run: djlint . --check
      - name: Check Javascript and CSS formatting
        run: npx prettier --check "**/*.{js,css}"
      - name: Check for typos
        uses: crate-ci/typos@v1.27.2
        with:
          config: ./typos.toml
      - name: Run tests
        run: python manage.py test
