name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  POSTGRES_DB: TURMFrontend
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      # Update output format to enable automatic inline annotations.
      - name: Check python code formatting with Run Ruff
        run: ruff check --output-format=github .
      - name: Check Django template formatting with djLint
        run: djlint . --check
      - name: Check for typos
        uses: crate-ci/typos@v1.27.2
        with:
          config: ./typos.toml
      - name: Run tests
        run: python manage.py test
