name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  POSTGRES_DB: TURMFrontend
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root
  NC_PORT: 8080
  NC_URL: http://localhost:8080
  NC_USER: admin
  NC_PASSWORD: admin
  DEBUG: "True"
  WEB_PORT: 8000
  DB_PORT: 5432
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@v1.27.2
        with:
          config: ./typos.toml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker containers
        run: docker compose --profile test build

      - name: Start database
        run: docker compose --profile test up -d db

      - name: Wait for database
        run: ./scripts/wait-for-it.sh localhost:5432 -t 120

      - name: Start Nextcloud
        run: docker compose --profile test up -d nextcloud

      - name: Wait for Nextcloud
        run: ./scripts/wait-for-it.sh nextcloud:8080 -t 120

      - name: Run migrations and populate data
        run: |
          docker compose exec -T web python manage.py migrate
          docker compose exec -T web python manage.py populate_observatories
          docker compose exec -T web python manage.py generate_admin_user

      - name: Check python code formatting
        run: docker compose exec -T web ruff format --check

      - name: Check for python lints
        run: docker compose exec -T web ruff check --output-format=github .

      - name: Check Django template formatting
        run: docker compose exec -T web djlint . --check

      - name: Run tests
        run: docker compose exec -T web python manage.py test

      - name: Cleanup
        run: docker compose down -v
